name: "Presidio CI Example"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: "" 
          MERGE_COMMIT_MESSAGE: pull-request-title
          UPDATE_METHOD: merge
